### ISSUE TITLE
Error loading mods on 0.18

### ISSUE THREAD

**Issue by TGNThump** [jodli/CreativeMod#24]
I'm getting the following message when loading the game with creative mod enabled.

```
Error while running setup for entity prototype "creative-mod_creative-lab" (lab). Entity must produce no item result result or mine to an item that isn't hidden when next_upgrade is set.
```

**Comment by jodli** [comment]
This was an incompatibility with the "Built-in-Beacons" mod.
I've fixed this for the 1.3.3 update and asked the mod author if this behavior is intended.

Thanks for reporting! :)
