### ISSUE TITLE
Missing 'tile' in raised event

### ISSUE THREAD

**Issue by Klonan** [jodli/CreativeMod#27]
https://github.com/jodli/CreativeMod/blob/fe91dc4eab41c61375a6abfe7094ac298522cd38/scripts/magic-wand-creator.lua#L463

The API docs say that the event should have `tile`:
https://lua-api.factorio.com/latest/events.html#on_player_built_tile

```
on_player_built_tile

Called after a player builds tiles.

Contains
player_index :: uint
surface_index :: uint: The surface the tile(s) were built on.
tiles :: array of OldTileAndPosition: The position data.
tile :: LuaTilePrototype: The tile prototype that was placed.
item :: LuaItemPrototype (optional): The item type used to build the tiles
stack :: LuaItemStack (optional): The stack used to build the tiles (may be empty if all of the items where used to build the tiles).
```

**Comment by jodli** [comment]
Hey!

I've changed the call after updating the mod to Factorio 0.18.27.
Now it's like this:

`surface.set_tiles(tiles_to_be_created, magic_wand_creator.get_tile_correction(player), true, true, true)`
