### ISSUE TITLE
Crashes at deconstruct

### ISSUE THREAD

**Issue by DrMagPie** [jodli/CreativeMod#29]
Factorio v0.18.27 
CreativeMod v1.4.0
<img width="358" alt="Screenshot 2020-05-27 at 22 46 43" src="https://user-images.githubusercontent.com/23652900/83065491-3daecf00-a06c-11ea-9558-724fa7f00f94.png">

**Comment by Crow08** [comment]
Fixed in PR #30 😉

**Comment by jodli** [comment]
Thanks for the notice and the PR! :)
Unfortunately I just yet saw this and I think I've already fixed it.

There was a lot more going on with raised script events, but I hope I found most of the stuff and have a somewhat stable version right now...
