### ISSUE TITLE
Pasted matter sources/voids don't work

### ISSUE THREAD

**Issue by quantumdude836** [jodli/CreativeMod#31]
When pasting a matter source/void (either via Ctrl+V, blueprint, or undo), the entity does not work at all (i.e. no items are placed on belts by sources, and no items are removed from belts by voids).

Changing the source/void settings doesn't fix it: only removing and placing (via left click) the entity restores functionality.

This issue seems to be new to 1.4.2 - possible regression, or it could be due to a recent Factorio change.

**Comment by jodli** [comment]
Should be fixed in 1.4.3!

Thanks for reporting this.

**Comment by quantumdude836** [comment]
Forgot to mention - looks like fluid sources/voids are the same way. Will they also be fixed?

**Comment by jodli** [comment]
Yes everything that is revived by the instant construction robots was lost in the new events and never registered in the tables.

So fluid source and void should work again as well.
