### ISSUE TITLE
Factorio v1.1 support

### ISSUE THREAD

**Issue by rutsky** [jodli/CreativeMod#35]
Hi!

Factorio v1.1 experimental is out.

It would be nice to adapt Creative Mod to support it.

Thanks!

**Comment by jodli** [comment]
I'll have a look right now! :)

**Comment by jodli** [comment]
Fixed in 90f62d2177267abfea36fcb68c9feb13d14cfe0c.

Creative Mod v1.7.0 should be available in the mod portal!
