### ISSUE TITLE
non-recoverable error when clicking "Disable all" on Team Cheats panel?

### ISSUE THREAD

**Issue by kirazy** [jodli/CreativeMod#36]
![](https://i.imgur.com/vxyWTRI.png)

I clicked "Disable all".

Reproduction steps: Creative Mod version 1.7.0, Factorio 1.1.0, create a new game, default settings, enable cheats, navigate to Team Cheats and click "Disable All".

**Comment by jodli** [comment]
Hi!

This should be fixed in v1.7.1.

Thanks for reporting! <3
