### ISSUE TITLE
non-recoverable error on save load

### ISSUE THREAD

**Issue by kajak96** [jodli/CreativeMod#42]
The mod Creative Mod (1.8.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event creative-mod::on_configuration_changed
LuaItemPrototype API call when LuaItemPrototype was invalid.
stack traceback:
	[C]: in function '__index'
	__creative-mod__/scripts/creative-chest-util.lua:314: in function 'set_chest_filter'
	__creative-mod__/scripts/events.lua:205: in function <__creative-mod__/scripts/events.lua:73>

**Comment by jodli** [comment]
Most likely not an issue anymore. Please create a new issue if you encounter this error again.

Thanks for your help! <3
